[WIP] libauthen-radius-perl: upgrade 0.22 -> 0.30
* ptest still needs work
* Upstream author has changed from MANOWAR to PORTAONE
* Update HOMEPAGE and SRC_URI
* Drop redundant DEPENDS on perl
* Drop redundant RDEPENDS on PN
* Drop patch for test.pl script, no longer applicable
* Add ptest dependencies
* Inherit ptest-perl.bbclass

Upstream release notes:

0.30 Mon Jun 10 17:21:42 2019
    - Fixed warning when NodeList parameter used without Host

0.29 Fri Nov 30 11:54:42 2018
    - Fix tests if FreeRADIUS dictionary not available

0.28 Thu Nov 29 14:24:42 2018
    - Fixed tagged integer attribute encoding (reported by Alexander Bechikov)

0.27 Fri Jul 06 12:28:42 2018
    - Force FreeRADIUS dictionary format when BEGIN-VENDOR directive is found
    - Load included files using the requested format
    - Added full support for octets type

0.26 Mon Dec 12 13:12:32 2016
    - Tag 0.25.1 as 0.26, because 0.25.1 is considered as 0.025001 (less than existing 0.25)

0.25.1 Thu Dec 08 14:38:44 2016
    - Require Perl v5.10+
    - Fixed warnings in tests
    - Fix sublist attribute type encoding

0.25 Tue Dec 06 12:25:00 2016
    - Added support for Status-Server requests (RFC 5997)
    - Added support for IPv6 (RFC 3162)
    - Added support for integer64 type (RFC 6929)
    - Fixed warning of using uninitialized value $vendor_name (RT 99161)
    - Added support for date and time types (RT 91408)
    - Improved support for FreeRADIUS and GNU Radius dictionary files
    - Added support for tagged attributes (RFC 2868)

0.24 Wed Oct 30 13:21:00 2013
    - Added support for changing I/O activity timeouts, so that
      custom retransmission policies can be implemented
    - Added ACCESS_CHALLENGE packet type definition (thanks to
      Stephane Billiart for the patch)
    - Fix the excessive wait on processing broadcasts when
      at least one of the nodes in node list did not listen on
      the requested port (a side-effect is that it is now possible
      to set timeout in floating seconds since the epoch)

0.23 Sat Aug 17 21:48:00 2013
    - Clear authenticator as a part of clear_attibutes(), so
      multiple requests, sent using the same object, will have
      different authenticators (as they should)

Signed-off-by: Tim Orling <timothy.t.orling@linux.intel.com>

diff --git a/meta-perl/recipes-perl/libauthen/libauthen-radius-perl/run-ptest b/meta-perl/recipes-perl/libauthen/libauthen-radius-perl/run-ptest
--- a/meta-perl/recipes-perl/libauthen/libauthen-radius-perl/run-ptest
+++ b/meta-perl/recipes-perl/libauthen/libauthen-radius-perl/run-ptest
@@ -13,8 +13,22 @@ systemctl restart radiusd || /etc/init.d/radiusd restart || {
         exit 1
 }
 
-# run teests
-perl test.pl
+# run tests
+# FIXME: this is from ptest-perl.bbclass and might not be correct
+for case in `find t -type f -name '*.t'`; do
+    perl $case >$case.output 2>&1
+    ret=$?
+    cat $case.output
+    if [ $ret -ne 0 ]; then
+        echo "FAIL: ${case%.t}"
+    elif grep -i 'SKIP' $case.output; then
+        echo "SKIP: ${case%.t}"
+    else
+        echo "PASS: ${case%.t}"
+    fi
+
+    rm -f $case.output
+done
 
 # restore the config and restart
 mv ${CONF_USERS}_orig ${CONF_USERS}
